apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-es
  namespace: rideshare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: rideshare/production/redis/credentials
        property: REDIS_URL

    - secretKey: password
      remoteRef:
        key: rideshare/production/redis/credentials
        property: redis-password
