apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::287872994236:role/rideshare-prod-use1-cert-manager-role
  creationTimestamp: "2026-08-17T07:27:29Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: cert-manager
  namespace: cert-manager
  resourceVersion: "651089"
  uid: 27e4efc1-10c6-4e3c-8c2c-7220ff78b175
