apiVersion: v1
kind: Namespace
metadata:
  name: database-migration
  labels:
    app.kubernetes.io/part-of: rideshare-platform
    platform.rideshare.io/layer: data-migration
    environment: production
