apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/part-of: rideshare-platform
    platform.rideshare.io/layer: ingress

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/part-of: rideshare-platform
    platform.rideshare.io/layer: security

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/part-of: rideshare-platform
    platform.rideshare.io/layer: security

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: rideshare-platform
    platform.rideshare.io/layer: observability

---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/part-of: rideshare-platform
    platform.rideshare.io/layer: observability

---
apiVersion: v1
kind: Namespace
metadata:
  name: rideshare
  labels:
    app.kubernetes.io/part-of: rideshare-platform
    platform.rideshare.io/layer: application
