apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
data:
  NEXT_PUBLIC_DRIVER_API: {{ .Values.config.NEXT_PUBLIC_DRIVER_API | quote }}
  NEXT_PUBLIC_RIDER_API: {{ .Values.config.NEXT_PUBLIC_RIDER_API | quote  }}
  NEXT_PUBLIC_TRIP_API: {{ .Values.config.NEXT_PUBLIC_TRIP_API | quote }}
  NEXT_PUBLIC_MATCHING_API: {{ .Values.config.NEXT_PUBLIC_MATCHING_API | quote }}
  NEXT_PUBLIC_WS_URL: {{ .Values.config.NEXT_PUBLIC_WS_URL | quote }}
