apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rider-service-es
  namespace: rideshare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rider-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: rideshare/rider-service-secret
        property: JWT_SECRET
