apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    app.kubernetes.io/name: rideshare-db-credentials
    app.kubernetes.io/part-of: rideshare-platform
  name: rideshare-db-credentials
  namespace: rideshare
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: rideshare/production/database/credentials
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: rideshare-db-credentials
