apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-service-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: {{ .Values.config.PORT | quote  }}
  DEBUG: {{ .Values.config.DEBUG  | quote }}
