global:
  namespace: rideshare
  domain: rideshare.lukmonadeokun.com

  environment: production

frontend:
  image:
    repository: 287872994236.dkr.ecr.us-east-1.amazonaws.com/rideshare/frontend

driver-service:
  image:
    repository: 287872994236.dkr.ecr.us-east-1.amazonaws.com/rideshare/driver-service

  config:
    REDIS_HOST: "master.rideshare-prod-use1-redis.zjqim0.use1.cache.amazonaws.com"
    REDIS_PORT: "6379"
    REDIS_TLS: "true"

rider-service:
  image:
    repository: 287872994236.dkr.ecr.us-east-1.amazonaws.com/rideshare/rider-service

  config:
    REDIS_HOST: "master.rideshare-prod-use1-redis.zjqim0.use1.cache.amazonaws.com"
    REDIS_PORT: "6379"
    REDIS_TLS: "true"

trip-service:
  image:
    repository: 287872994236.dkr.ecr.us-east-1.amazonaws.com/rideshare/trip-service

matching-service:
  image:
    repository: 287872994236.dkr.ecr.us-east-1.amazonaws.com/rideshare/matching-service

  config:
    TRIP_SERVICE_URL: "http://trip-service:3005"
  # REDIS_HOST: "master.rideshare-prod-use1-redis.zjqim0.use1.cache.amazonaws.com"
  # REDIS_PORT: "6379"
  # REDIS_TLS: "true"

email-service:
  image:
    repository: 287872994236.dkr.ecr.us-east-1.amazonaws.com/rideshare/email-service
