apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::287872994236:role/rideshare-prod-use1-cluster-autoscaler-role
  creationTimestamp: "2026-08-15T18:50:37Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: cluster-autoscaler-sa
  namespace: kube-system
  resourceVersion: "16927"
  uid: 2160c480-c8eb-4c39-bd93-b55b17600068
