apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rideshare-prod-use2-health-tls
  namespace: rideshare
spec:
  secretName: rideshare-prod-use2-health-tls

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - use2.rideshare.lukmonadeokun.com
