USER-SUPPLIED VALUES:
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: external-secrets
        topologyKey: kubernetes.io/hostname
      weight: 100
certController:
  nodeSelector:
    workload-type: platform
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  tolerations:
  - effect: NoSchedule
    key: workload-type
    operator: Equal
    value: platform
installCRDs: true
nodeSelector:
  workload-type: platform
replicaCount: 2
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceAccount:
  create: false
  name: external-secrets
tolerations:
- effect: NoSchedule
  key: workload-type
  operator: Equal
  value: platform
webhook:
  nodeSelector:
    workload-type: platform
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  tolerations:
  - effect: NoSchedule
    key: workload-type
    operator: Equal
    value: platform
