apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::287872994236:role/rideshare-prod-use1-external-secrets-role
  creationTimestamp: "2026-08-17T09:28:33Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: external-secrets
  namespace: external-secrets
  resourceVersion: "708000"
  uid: 871d7898-2233-4a10-9259-19ecde0104b8
