apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    force-sync: "1786963514"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1","kind":"ExternalSecret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"external-secrets","app.kubernetes.io/name":"eso-validation","app.kubernetes.io/part-of":"rideshare-platform"},"name":"eso-validation","namespace":"rideshare"},"spec":{"data":[{"remoteRef":{"key":"rideshare/production/test/eso-validation","property":"username"},"secretKey":"username"},{"remoteRef":{"key":"rideshare/production/test/eso-validation","property":"password"},"secretKey":"password"},{"remoteRef":{"key":"rideshare/production/test/eso-validation","property":"environment"},"secretKey":"environment"}],"refreshInterval":"1h","secretStoreRef":{"kind":"ClusterSecretStore","name":"aws-secrets-manager"},"target":{"creationPolicy":"Owner","deletionPolicy":"Retain","name":"eso-validation"}}}
  creationTimestamp: "2026-08-17T10:39:20Z"
  finalizers:
  - externalsecrets.external-secrets.io/externalsecret-cleanup
  generation: 1
  labels:
    app.kubernetes.io/managed-by: external-secrets
    app.kubernetes.io/name: eso-validation
    app.kubernetes.io/part-of: rideshare-platform
  name: eso-validation
  namespace: rideshare
  resourceVersion: "731235"
  uid: e6db63a5-d8af-4ce8-a776-a2a4678e210e
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: rideshare/production/test/eso-validation
      metadataPolicy: None
      property: username
    secretKey: username
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: rideshare/production/test/eso-validation
      metadataPolicy: None
      property: password
    secretKey: password
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: rideshare/production/test/eso-validation
      metadataPolicy: None
      property: environment
    secretKey: environment
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: eso-validation
status:
  binding:
    name: eso-validation
  conditions:
  - lastTransitionTime: "2026-08-17T10:39:20Z"
    message: secret synced
    reason: SecretSynced
    status: "True"
    type: Ready
  refreshTime: "2026-08-17T10:45:18Z"
  syncedResourceVersion: 1-faf49045ae529918278e676b6625056dd2cb456e2997439d61a345ff
