apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matching-service-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: matching-service
